services:
  postgres:
    image: postgres:16
    container_name: crud_springboot_auth_ci_cd_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - crud_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  crud_postgres_data: