spring.application.name=crud-springboot-auth-ci-cd
spring.output.ansi.enabled=ALWAYS
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
server.port=3000
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false